on:
  push:
    branches: master
jobs:
    deploy_job:
     runs-on: ubuntu-latest
     name: deploy
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: 'chmod -R 777 storage/'
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
         username: 'ubuntu'
         server: '13.234.18.200'
         port: '22'
         remote_path: '/var/www/html/'
         sftp_only: true
         password: '123456'
