name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Premad@2417
          MYSQL_DATABASE: molni2j8_stucard
          MYSQL_USER: molni2j8_ibrahim
          MYSQL_PASSWORD: Premad@2417
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Optional: Run Migrations if needed before deployment
    - name: Wait for MySQL
      run: sudo apt-get install -y netcat && while ! nc -z localhost 3306; do sleep 1; done
    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: molni2j8_stucard
        DB_USERNAME: molni2j8_ibrahim
        DB_PASSWORD: Premad@2417
      run: php artisan migrate --force

    - name: Deploy to Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "./"
        server-dir: "/stucard/"
        port: ${{ secrets.FTP_PORT }}

    - name: Run Remote Commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          cd /stucard
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
